# Dockerfile-backend
FROM python:3.11-slim

WORKDIR /app

# Copy only what's needed
COPY fastapi_app.py .
COPY requirements.txt .
COPY src ./src
RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8000

CMD ["uvicorn", "fastapi_app:app", "--host", "0.0.0.0", "--port", "8000"]