
# Dockerfile-frontend
FROM python:3.11-slim

WORKDIR /app

# Copy only what's needed
COPY streamlit_app.py .
COPY requirements.txt .
COPY src ./src
RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8501

CMD ["streamlit", "run", "streamlit_app.py", "--server.port=8501", "--server.address=0.0.0.0"]
